install.packages(c('testthat', 'vdiffr', 'spelling','covr','remotes'), repos = 'http://cran.us.r-project.org')
install.packages('https://github.com/Open-Systems-Pharmacology/rClr/releases/download/v0.9.1/rClr_0.9.1.zip', repos = NULL, type = 'binary')
download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.tar.gz?pr=false', destfile = 'ospsuite.utils.tar.gz', mode='wb')
remotes::install_local('ospsuite.utils.tar.gz', dependencies = c('Depends', 'Imports'), upgrade = 'never')
unlink('ospsuite.utils.tar.gz')
download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.tar.gz?pr=false', destfile = 'tlf.tar.gz', mode='wb')
remotes::install_local('tlf.tar.gz', dependencies = c('Depends', 'Imports'), upgrade = 'never')
unlink('tlf.tar.gz')
