install.packages(c('testthat', 'vdiffr', 'spelling','covr','remotes'), repos = 'http://cran.us.r-project.org', type='win.binary')
download.file('https://github.com/Open-Systems-Pharmacology/rSharp/releases/download/v1.0.0/rSharp-v1.0.0-Windows-r_4.4.0.zip', destfile = "rsharp.zip", mode = "wb")
unzip("rsharp.zip")
rSharp_archive <- list.files( pattern = "rSharp.*\\.zip")
install.packages(rSharp_archive, repos = NULL, type = "binary")
unlink(c("rsharp.zip", rSharp_archive))
download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip?pr=false', destfile = 'ospsuite.utils.zip', mode='wb')
install.packages('ospsuite.utils.zip', repos = NULL, type = 'binary')
unlink('ospsuite.utils.zip')
download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.tar.gz?pr=false', destfile = 'tlf.tar.gz', mode='wb')
remotes::install_local('tlf.tar.gz', dependencies = c('Depends', 'Imports'), upgrade = 'never')
unlink('tlf.tar.gz')
