name: Update renv snapshot and check package

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read

jobs:
  update-renv-nightly:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/update-renv-lockfile.yaml@main
    with:
      app-id: ${{ vars.VERSION_BUMPER_APPID }}
    secrets:
      private-key: ${{ secrets.VERSION_BUMPER_SECRET }}
